serviceDiscovery has been added.
enterprisedlt/fabric-chaincode-client pull request #3
Opened 2020-04-07 12:11 UTC by maksimfedin

2020-04-12 18:46 UTC, maksimfedin commented
@apolubelov pls consider to merge.

2020-04-12 22:03 UTC, apolubelov commented on src/main/scala/org/enterprisedlt/fabric/client/FabricChannel.scala
> +    def getChainCode(name: String, codec: BinaryCodec, chaincodeServiceDiscovery: Boolean /* TODO: , endorsementTimeout: Int = */): FabricChainCode =
put default false for discovery

2020-04-13 08:02 UTC, apolubelov requested changes

2020-04-13 08:02 UTC, apolubelov commented on src/main/scala/org/enterprisedlt/fabric/client/FabricChannel.scala
> +    def addClientCerts(clientCertFile: String, clientKeyFile: String): Unit = {
should be in constructor

2020-04-13 08:02 UTC, apolubelov commented on src/main/scala/org/enterprisedlt/fabric/client/FabricClient.scala
> +            }
the role has to be in peer config

2020-04-13 08:02 UTC, apolubelov commented on src/main/scala/org/enterprisedlt/fabric/client/configuration/PeerConfig.scala
> +    peerServiceDiscovery: Boolean,
model roles here instead of just discovery flag

2020-04-13 08:04 UTC, maksimfedin commented on src/main/scala/org/enterprisedlt/fabric/client/FabricChannel.scala
> +    def addClientCerts(clientCertFile: String, clientKeyFile: String): Unit = {
I'm going to remove this method.

2020-04-13 10:27 UTC, maksimfedin commented on src/main/scala/org/enterprisedlt/fabric/client/FabricClient.scala
> +            }
done.

2020-04-13 10:27 UTC, maksimfedin commented on src/main/scala/org/enterprisedlt/fabric/client/configuration/PeerConfig.scala
> +    peerServiceDiscovery: Boolean,
done.

2020-04-13 10:29 UTC, maksimfedin commented on src/main/scala/org/enterprisedlt/fabric/client/FabricChannel.scala
> +    def getChainCode(name: String, codec: BinaryCodec, chaincodeServiceDiscovery: Boolean /* TODO: , endorsementTimeout: Int = */): FabricChainCode =
done.

2020-04-15 12:45 UTC, apolubelov approved these changes

2020-04-15 12:45 UTC, merged